twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        'public/images': images
    form_themes:
        - 'bootstrap_4_layout.html.twig'
    globals:
        pathToCSS: "%kernel.project_dir%/public/css"
        pathToImages: "%kernel.project_dir%/public/images"
        pathToFonts: "%kernel.project_dir%/public/fonts"
